BEGIN
FOR cur_rec IN (SELECT object_name, object_type
                     FROM user_objects
                    WHERE object_type IN
                             ('TABLE',
                              'VIEW',
                              'PACKAGE',
                              'PROCEDURE',
                              'FUNCTION',
                              'SEQUENCE',
                              'MATERIALIZED VIEW'
                             ))
   LOOP
      BEGIN
IF cur_rec.object_type = 'TABLE'
         THEN
EXECUTE IMMEDIATE    'DROP '
                              || cur_rec.object_type
                              || ' "'
                              || cur_rec.object_name
                              || '" CASCADE CONSTRAINTS PURGE';
ELSE
EXECUTE IMMEDIATE    'DROP '
                              || cur_rec.object_type
                              || ' "'
                              || cur_rec.object_name
                              || '"';
END IF;
EXCEPTION
         WHEN OTHERS
         THEN
            DBMS_OUTPUT.put_line (   'FAILED: DROP '
                                  || cur_rec.object_type
                                  || ' "'
                                  || cur_rec.object_name
                                  || '"'
                                 );
END;
END LOOP;
END;
/

COMMIT;
-- empty the trash
PURGE RECYCLEBIN;
COMMIT;

CREATE TABLE employee
(
    employee_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    firstname   VARCHAR(256),
    lastname    VARCHAR(256),
    address     VARCHAR(256),
    city        VARCHAR(256),
    postcode    VARCHAR(256),
    salary      NUMERIC(10, 2),
    company_id  INTEGER,
    CONSTRAINT employee_id_pk primary key (employee_id)
);

CREATE TABLE product_range
  (
     product_range_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
     name             VARCHAR(256),
     CONSTRAINT product_range_id_pk primary key (product_range_id)
  );

CREATE TABLE address
  (
     address_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
     address    VARCHAR(40),
     street     VARCHAR(40),
     city       VARCHAR(25),
     state      CHAR(2),
     zipcode    VARCHAR(10),
     country    VARCHAR(20),
     CONSTRAINT address_id_pk primary key (address_id)
  );

CREATE TABLE item
  (
     item_id          INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
     name             VARCHAR(256),
     price            NUMERIC(10, 2),
     product_range_id INTEGER,
     CONSTRAINT aitem_id_pk primary key (item_id),
     CONSTRAINT product_range_id_fk FOREIGN KEY (product_range_id) REFERENCES product_range(product_range_id)
  );

CREATE TABLE customer
(
    customer_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name        VARCHAR(30),
    telephone   VARCHAR(20),
    address_id  INTEGER,
    CONSTRAINT customer_id_pk primary key (customer_id),
    FOREIGN KEY (address_id) REFERENCES address(address_id)
);

CREATE TABLE salesorder
  (
     order_id    INTEGER PRIMARY KEY,
     customer_id INTEGER,
     employee_id INTEGER,
     item_id     INTEGER,
     order_date  DATE,
     ship_date   DATE,
     payment     NUMERIC(10, 2),
     FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
     FOREIGN KEY (employee_id) REFERENCES employee(employee_id),
     FOREIGN KEY (item_id) REFERENCES item(item_id)
  );